### PR TITLE
fix #503 adds --memo option to 'call' command

### LINKED ISSUE #503: Can't schedule non JSON call
***Describe the bug***
 Can't schedule a function call that takes arguments not in JSON format, e.g. raw string. 

***To Reproduce***
 ```bash
 near call exchange.m0 exchange_deposit 'USER_123' --accountId=<ACCOUNT_ID>
 ```

***Expected behavior***
 A function call successfully executed without crashing. Or telling me to use argument like `--raw_input`

***Screenshots***
 ```bash
 near call exchange.m0 exchange_deposit 'USER_123' --accountId=m0 --amount=0.1
 ```

```
 Scheduling a call: exchange.m0.exchange_deposit(USER_123) with attached 0.1 NEAR
 Error: SyntaxError: Unexpected token U in JSON at position 0
 at JSON.parse (<anonymous>)
 at scheduleFunctionCall (/Users/ekwork/.config/yarn/global/node_modules/near-shell/commands/call.js:31:14)
 at processTicksAndRejections (internal/process/task_queues.js:93:5)
 at async Object.handler (/Users/ekwork/.config/yarn/global/node_modules/near-shell/utils/exit-on-error.js:37:9)
 ```

***Desktop (please complete the following information):***

*   OS: MacOS
*   Version `0.24.9`
*   NEAR_ENV=testnet

***Additional context***
 This is needed to support exchange deposits with a custom memo message.

### PR DESCRIPTION
**Pull request by luciotato**
with this addition, the exchange-hot-wallet contract call mentioned in #503 by @evgenykuzyakov becomes:

`near call exchange.m0 exchange_deposit --memo 'USER_123' --accountId=m0 --amount=0.1`

### CODE REVIEW

**Comment by vgrichina** [comment]
@luciotato not sure I understand the change.

Here you mention:
https://github.com/near/near-cli/issues/503#issuecomment-685954525

> What I don't see possible is to do this:
>
>     near call exchange.m0 exchange_deposit 'USER_123' --accountId=m0 --amount=0.1
> without converting it to JSON maybe using a default parameter name, as in:
>
>     near call exchange.m0 exchange_deposit '{"data":"USER_123"}' --accountId=m0 --amount=0.1

However implementation seems to be to still avoid passing as is vs 

>     if (options.memo) options.args=`{"":"${options.memo}"}`;

What is the intended receiver contract for such format?

**Comment by vgrichina** [comment]
BTW for more context here's somewhat related proposal for base64 arguments:

https://github.com/near/near-cli/pull/614

**Comment by luciotato** [comment]
>What is the intended receiver contract for such format?

The exchange-deposit-receiver core-contract as indicated here: https://github.com/near/core-contracts/tree/master/exchange-deposit-receiver#api-examples

It reads:

>As a temporary workaround, the above command can be changed to
`near call coin_exchange exchange_deposit '{"": "USER_123"}' --accountId=token_owner --amount=10`

So this fix is just "syntax sugar", so the user can write:
`near call coin_exchange exchange_deposit --memo 'USER_123' --accountId=token_owner  --amount=10`
instead of writing:
`near call coin_exchange exchange_deposit '{"": "USER_123"}' --accountId=token_owner --amount=10`

**Comment by luciotato** [comment]
can you merge this please?

**Comment by ilblackdragon** [comment]
@luciotato that contract is not used by anyone and not planned to, or am I mistaken?

**Comment by mikedotexe** [comment]
> @luciotato that contract is not used by anyone and not planned to, or am I mistaken?
> I would suggest to not merge it and close it at this point.

This is my understanding as well. Sorry for the delay, Lucio. I think it makes sense to close this one, but thank you for leaning in.

**Pull request closed without merging**
