### PR TITLE
epoch converted to number in 'near validators <epoch>'

### PR DESCRIPTION
**Pull request by volovyk-s**
closing #666

### CODE REVIEW

**Review by bowenwang1996 — COMMENTED** [review]
I am not sure what this is supposed to do. Epoch id is not an integer and cannot be parsed as such

**Comment by volovyk-s** [comment]
@bowenwang1996 looks like the function parameter should be called `blockNumber` (Docs: https://docs.near.org/docs/api/rpc#detailed-validator-status). And it should be a number, not a string. Thanks for pointing this out!
P.S. Check the attached issue for more context.

**Comment by vgrichina** [comment]
> @bowenwang1996 looks like the function parameter should be called `blockNumber` (Docs: https://docs.near.org/docs/api/rpc#detailed-validator-status). And it should be a number, not a string. Thanks for pointing this out!

@volovyk-s looks like there is opportunity to pass block hash as well – we should support either IMO. 

Note that in case you want to have `yargs` always parse some option into number there is such possibility:
https://github.com/yargs/yargs/blob/master/docs/api.md#numberkey

(won't work for the case when you need to support both block hash and number though)

**Comment by volovyk-s** [comment]
> > @bowenwang1996 looks like the function parameter should be called `blockNumber` (Docs: https://docs.near.org/docs/api/rpc#detailed-validator-status). And it should be a number, not a string. Thanks for pointing this out!
> 
> @volovyk-s looks like there is opportunity to pass block hash as well – we should support passing either IMO.
> 
> Note that in case you want to have `yargs` always parse some option into number there is such possibility:
> https://github.com/yargs/yargs/blob/master/docs/api.md#numberkey
> 
> (won't work for the case when you need to support both block hash and number though)

Updated.
To avoid breaking changes I have not added new options (--blockHash and --blockNumber).

**Pull request merged**
