### PR TITLE
Save account credentials with generate-key --seedPhrase option

### PR DESCRIPTION
**Pull request by kucharskim**
I was able to generate account.json credentials file from seed phrase,
received when I was initially setting up account via official NEAR web
wallet.

      env NODE_ENV=mainnet near generate-key --seedPhrase 'secret recovery phrase' account

I find it very convenient. This addresses https://github.com/near/near-cli/issues/570

### CODE REVIEW

**Comment by kucharskim** [comment]
If there is something more to test, let me know.

**Comment by mikedotexe** [comment]
> If there is something more to test, let me know.

thank you so much! I'll try to get to this today

**Comment by kucharskim** [comment]
> thank you so much! I'll try to get to this today

I think I would need to update also https://docs.near.org/docs/development/near-cli as that documentation would be incorrect with the behavior of the near-cli after this pull request is merged.

**Review by mikedotexe — APPROVED** [review]
great stuff, thank you!

**Comment by mikedotexe** [comment]
> > thank you so much! I'll try to get to this today
> 
> I think I would need to update also https://docs.near.org/docs/development/near-cli as that documentation would be incorrect with the behavior of the near-cli after this pull request is merged.

cc @thisisjoshford

**Pull request merged**
